name: pkg-cleanup-pr

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:

  cleanup-pr-pkgs:
    name: Delete old unused container images
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Delete PR older than a week
        uses: snok/container-retention-policy@v2
        with:
          image-names: dns-base
          cut-off: now UTC
          account-type: org
          org-name: joris-me
          untagged-only: false
          filter-tags: pr-${{ github.event.number }}
          skip-tags: latest, master, v*
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
  